default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: your_project_production
  username: <%= ENV['YOUR_PROJECT_DATABASE_USER'] %>
  password: <%= ENV['YOUR_PROJECT_DATABASE_PASSWORD'] %>
  host: <%= ENV['YOUR_PROJECT_DATABASE_HOST'] %>

test:
  <<: *default
  database: your_project_test
  username: your_username
  password: your_password
  host: localhost

production:
  <<: *default
  database: your_project_production
  username: <%= ENV['YOUR_PROJECT_DATABASE_USER'] %>
  password: <%= ENV['YOUR_PROJECT_DATABASE_PASSWORD'] %>
  host: <%= ENV['YOUR_PROJECT_DATABASE_HOST'] %>

